### DISCUSSION TITLE
pure json data to jsonb field

### DISCUSSION THREAD

**Discussion by edib** [rapidloop/rapidrows#4] [General]
I have following data posted as a json and I want it to put into a single jsonb field. 

How can I achieve that? 

[
  {
    "sensors": [
      {
        "type": "air_sensor",
        "temperature": 2,
        "humidity": 45,
        "code": "dht11",
        "id": 10001
      },
      {
        "type": "soil_sensor",
        "soil_moisture": 354,
        "code": "EIS10698",
        "id": 10002
      }
    ],
    "id": "324sre43bv5345v45v346tvb3",
    "mac": "..."
  }
]

**Comment by mdevan** [comment]
(Sorry for late reply. Also converted this to a discussion.)

Assuming a table created like this:

```sql
create table t1 (at timestamptz default current_timestamp, data jsonb);
```

Here is a RapidRows configuration yaml:

```yaml
version: '1'
endpoints:
- uri: /report-data
  implType: exec
  datasource: default
  script: INSERT INTO t1 (data) VALUES ($1::jsonb)
  params:
  - name: data
    in: body
    type: string
    required: true
datasources:
- name: default
  dbname: mdevan
```

You can POST to the endpoint like so:

```
$ curl -i -X POST http://localhost:8080/report-data -H 'Content-Type: application/x-www-form-urlencoded' -d 'data=[{"sensors": [{"type": "air_sensor","temperature": 2,"humidity": 45,"code": "dht11","id": 10001}]}]'
HTTP/1.1 200 OK
Content-Type: application/json
Date: Mon, 28 Nov 2022 14:01:58 GMT
Content-Length: 24

{
  "rowsAffected": 1
}
```

with a result like:

```
mdevan=> select * from t1;
                at                |                                                  data
----------------------------------+---------------------------------------------------------------------------------------------------------
 2022-11-28 19:31:58.719802+05:30 | [{"sensors": [{"id": 10001, "code": "dht11", "type": "air_sensor", "humidity": 45, "temperature": 2}]}]
(1 row)
```

Is this what you want to do?
